name: Code Quality

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  check:
    uses: drehelis/improved-chainsaw/.github/workflows/code-quality.yml@main
    with:
      build: true
      prettier: true
      lint: false
      type-check: true